version: "3"
services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - php:php

  php:
    build: ./php
    restart: always
    expose:
      - "9000"
    links:
      - redis
    volumes:
      - ./public:/usr/share/nginx/html
      - ./src:/usr/share/nginx/src

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data
    command: redis-server --appendonly yes
