<?php include "partials/header.phtml";?>
<br><br>
<h1 class="cover-heading center">Software Developer Homework</h1>
<br><br>
<h3>1. URL shortener</h3>
<br>

<p class="lead">Implement URL shortener web-application, using programming languages, and databases your choice.</p>
<p class="lead"><b>You are not allowed to use frameworks such as symphony, Django etc.</b></p>
<p class="lead">Index page should display a form offering user to shorten a URL. After form was submitted, short URL should be displayed to the user.</p>
<p class="lead">Short URLs should redirect to original URLs.</p>
<p class="lead">Your implementation should be able to sustain 100 URL submissions and 1,000 short URL accesses per minute.</p>
<p class="lead">You may assume that there will be approximately 1,000,000 unique URLs and all further submissions will be duplicates of URLs submitted previously.</p>

<br><br>
<h3>2. Scale</h3>
<br>

<p class="lead">Assuming we want to scale it up to 10,000 URL submissions and 10,000,000 short URL accesses per second with up to 10,000,000,000 unique URLs.</p>
<p class="lead">Please add a note (as a separate document) summarizing what changes need to be done in your code to support such scale and how to set up such a system.</p>

<br><br>
<h3>3. Extras (optional)</h3>
<br>

<p class="lead">Include docker file in your solution. You can help us to better understand how you approach complex tasks by sending us a git repository containing all intermediate commits you made while working on this task. </p>

<?php include "partials/footer.phtml";?>