<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>URL Shortener</title>
	<script src="/assets/js/jquery-3.4.1.min.js"></script>
	<script src="/assets/js/popper.min.js"></script>
	<link href="/assets/css/bootstrap.min.css" rel="stylesheet">
	<script src="/assets/js/bootstrap.min.js"></script>
	<link href="/assets/img/favicon.jpg" type="image/jpeg" rel="shortcut icon">
	<link href="/assets/css/styles.css" rel="stylesheet">
	<script src="/assets/js/main.js"></script>
</head>
<body>

<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
	<header class="masthead mb-auto">
		<div class="inner">
			<h3 class="masthead-brand">URL Shortener</h3>
			<nav class="nav nav-masthead justify-content-center">
				<a class="nav-link active" href="/">Home</a>
				<a class="nav-link" href="https://gitlab.com/denysaw/shortener" target="_blank">Repository</a>
				<a class="nav-link" href="/task">Task</a>
			</nav>
		</div>
	</header>

	<main role="main" class="inner cover">